### PR TITLE
Update production.yml

### PR DESCRIPTION
**Pull request by andersbjergfelt**
Think ASPNETCORE_ENVIRONMENT=Development will collide with _env.IsDevelopment() in startup.cs. That is, it will use sqlite as db instead of SQL Server

### CODE REVIEW

**Comment by C0DK** [comment]
why are you using sqllite though? i mean - the whole point of docker etc, is that you can run the same setup *everywhere* - previously, regarding latest, we had a bug that was only a problem in mssql - not sqllite, so we didn't actaully catch it. Maybe what you want is a quicker way to hotswap the new c# version

**Comment by andersbjergfelt** [comment]
I agree with the same setup everywhere. Even though it is much easier running the solution locally with sqlite. 
I am in for the idea of connecting to the mssql docker service from outside when building the webservice manually. Let's do it.

**Comment by Trivivium** [comment]
Just to chime in... The environment variable makes sure `IsDevelopment()` returns `true`, so they do the same so to speak.

I also agree that it would be best if we can use the MS SQL Server from outside the Docker container.

**Comment by C0DK** [comment]
we should fix the development thing for sure if we are currently using sqlite3 in production. that is not so good

**Pull request merged**
